<a href="https://colab.research.google.com/github/Fridaya6661-Dev/Second-Project/blob/main/Feature%20engineering%20and%20modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Dataset and Take Some Information

In [ ]:
pip install catboost

     |████████████████████████████████| 76.3 MB 21 kB/s 


In [ ]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.svm import SVC


from sklearn.feature_selection import SelectKBest, f_classif, SelectFromModel
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV
from imblearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
import joblib

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_curve

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Friday6661/Dataset/main/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [ ]:
# Mengecheck Ukuran DataFrame
df.shape

(7043, 21)

In [ ]:
# Mengecheck nama kolom pada Dataframe
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
# Mengecheck tipe data dari setiap kolom
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
#Mengecheck jumlah missing value pada DataFrame
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Data Preprocessing

## Handling Data Inconsisten

In [ ]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.astype({'SeniorCitizen': 'object'}).dtypes

customerID           object
gender               object
SeniorCitizen        object
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [ ]:
df['SeniorCitizen'].replace(to_replace=1, value='Yes', inplace=True)
df['SeniorCitizen'].replace(to_replace=0,  value='No', inplace=True)

## Handling Missing Value

In [ ]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [ ]:
df = df.fillna(df.mean())

In [ ]:
data = df.iloc[:,1:]

data['Churn'].replace(to_replace='Yes', value=1, inplace=True)
data['Churn'].replace(to_replace='No',  value=0, inplace=True)

In [ ]:
X = data.drop(columns=['Churn'])
y = data.Churn

## Splitting Data

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5634, 19), (1409, 19), (5634,), (1409,))

# Simple Model

## Create Pipeline

In [ ]:
X_train.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [ ]:
pip install jcopml

     |████████████████████████████████| 100 kB 4.3 MB/s 
  Created wheel for jcopml: filename=jcopml-1.1.14-py2.py3-none-any.whl size=33655 sha256=5d1397c2db2bcad80d32be9b93188e7cd52df5432272c4dea9a852dcabcc4dc3
  Stored in directory: /root/.cache/pip/wheels/d9/6a/86/9a622c06f65732afe0e31c02a92fae6ab663ffd7162bcf5125
Successfully built jcopml


In [ ]:
from jcopml.tuning import grid_search_params as gsp

In [ ]:
nums = X.select_dtypes(include=['int64', 'float64']).columns

In [ ]:
cats = X.select_dtypes(include=['object', 'bool']).columns

In [ ]:
cat_encoder = lambda x : pd.get_dummies(x)

In [ ]:
categorical_pipeline = Pipeline([
                                  ('onehot', OneHotEncoder())
])

preprocessor = ColumnTransformer(transformers=[
                                  ('categoric', categorical_pipeline, cats)
])



In [ ]:
pipeline1 = Pipeline(steps=[('preprocessing', preprocessor),
                            ('scaling', StandardScaler()),
                            ('sampling', SMOTE()),
                            ('feature_selection', SelectFromModel(ExtraTreesClassifier(random_state=2), prefit=False)),
                            ('algo', RandomForestClassifier())
                           ])

In [ ]:
gsp.rf_params

{'algo__max_depth': [20, 50, 80],
 'algo__max_features': [0.3, 0.6, 0.8],
 'algo__min_samples_leaf': [1, 5, 10],
 'algo__n_estimators': [100, 150, 200]}

In [ ]:
parameter1 = {'algo__criterion' : ['gini', 'entropy'],
             'algo__max_depth': [20, 50, 80],
             'algo__max_features': [0.3, 0.6, 0.8],
             'algo__min_samples_leaf': [1, 5, 10],
             'algo__n_estimators': [100, 150, 200]
}

In [ ]:
model1 = GridSearchCV(pipeline1, param_grid=parameter1, cv=3, n_jobs=-1, verbose=1)
model1.fit(X_train, y_train)

Fitting 3 folds for each of 162 candidates, totalling 486 fits


GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('categoric',
                                                                         Pipeline(steps=[('onehot',
                                                                                          OneHotEncoder())]),
                                                                         Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies...
                                       ('scaling', StandardScaler()),
                                       ('sampling', SMOTE()),
                                       ('feature_selection',
                                        SelectFromModel(estimator=ExtraTreesClassifier(random_state=2))),
                           

In [ ]:
model1.best_estimator_.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('categoric',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod'],
      dtype='object'))])),
                ('scaling', StandardScaler()), ('sampling', SMOTE()),
                ('feature_selection',
                 SelectFromModel(estimator=ExtraTreesClassifier(random_state=2))),
                ('algo',
                 RandomForestClassifier(criterion='entropy', max_depth=50,
                                        max_features=0.8, min_samples_leaf=5,
        

In [ ]:
prediction1 = model1.best_estimator_.predict(X_test)
print(classification_report(y_test, prediction1))
print(confusion_matrix(y_test, prediction1))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83      1035
           1       0.54      0.58      0.56       374

    accuracy                           0.76      1409
   macro avg       0.69      0.70      0.69      1409
weighted avg       0.76      0.76      0.76      1409

[[848 187]
 [157 217]]


In [ ]:
filename1 = 'randomforest.pkl'
joblib.dump(model1.best_estimator_, filename1)

['randomforest.pkl']

In [ ]:
gsp.svm_params

{'algo__C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
 'algo__gamma': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])}

In [ ]:
parameter2 = {'algo__C': np.array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
              'algo__gamma': np.array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])
              }

In [ ]:
pipeline2 = Pipeline(steps=[('preprocessing', preprocessor),
                            ('scaling', StandardScaler()),
                            ('sampling', SMOTE()),
                            ('feature_selection', SelectFromModel(ExtraTreesClassifier(random_state=2), prefit=False)),
                            ('algo', SVC())
                           ])

In [ ]:
model2 = GridSearchCV(pipeline2, param_grid=parameter2, cv=3, n_jobs=-1, verbose=1)
model2.fit(X_train, y_train)

Fitting 3 folds for each of 49 candidates, totalling 147 fits


GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('categoric',
                                                                         Pipeline(steps=[('onehot',
                                                                                          OneHotEncoder())]),
                                                                         Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod'],
      dtype='object'))])),
                                       ('scaling', StandardScaler()),
                                       ('sampling', SMOTE()),
                                       ('feature_selection',
                                        SelectFrom

In [ ]:
prediction2 = model2.best_estimator_.predict(X_test)
print(classification_report(y_test, prediction2))
print(confusion_matrix(y_test, prediction2))

              precision    recall  f1-score   support

           0       0.78      0.96      0.86      1035
           1       0.67      0.25      0.36       374

    accuracy                           0.77      1409
   macro avg       0.72      0.60      0.61      1409
weighted avg       0.75      0.77      0.73      1409

[[989  46]
 [281  93]]


In [ ]:
gsp.xgb_params

{'algo__colsample_bytree': [0.4, 0.6, 0.8],
 'algo__gamma': [1, 5, 10],
 'algo__learning_rate': [0.01, 0.1, 1],
 'algo__max_depth': [3, 6, 10],
 'algo__n_estimators': [100, 150, 200],
 'algo__reg_alpha': [0.01, 0.1, 10],
 'algo__reg_lambda': [0.01, 0.1, 10],
 'algo__subsample': [0.4, 0.6, 0.8]}

In [ ]:
parameter3 = {'algo__colsample_bytree': [0.4, 0.6, 0.8],
              'algo__gamma': [1, 5, 10],
              'algo__learning_rate': [0.01, 0.1, 1],
              'algo__max_depth': [3, 6, 10],
              'algo__n_estimators': [100, 150, 200],
              'algo__reg_alpha': [0.01, 0.1, 10],
              }

In [ ]:
pipeline3 = Pipeline(steps=[('preprocessing', preprocessor),
                            ('scaling', StandardScaler()),
                            ('sampling', SMOTE()),
                            ('feature_selection', SelectFromModel(ExtraTreesClassifier(random_state=2), prefit=False)),
                            ('algo', XGBClassifier())
                           ])

In [ ]:
model3 = GridSearchCV(pipeline3, param_grid=parameter3, cv=3, n_jobs=-1, verbose=1)
model3_fit = model3.fit(X_train, y_train)

Fitting 3 folds for each of 729 candidates, totalling 2187 fits


In [ ]:
prediction3 = model3.predict(X_test)
print(classification_report(y_test, prediction3))
print(confusion_matrix(y_test, prediction3))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84      1035
           1       0.56      0.62      0.59       374

    accuracy                           0.77      1409
   macro avg       0.71      0.72      0.72      1409
weighted avg       0.78      0.77      0.77      1409

[[852 183]
 [141 233]]


In [ ]:
gsp.knn_params

{'algo__n_neighbors': array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]),
 'algo__p': [1, 1.5, 2],
 'algo__weights': ['uniform', 'distance']}

In [ ]:
parameter4 = {'algo__n_neighbors': np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]),
              'algo__p': [1, 1.5, 2],
              'algo__weights': ['uniform', 'distance']}

In [ ]:
pipeline4 = Pipeline(steps=[('preprocessing', preprocessor),
                            ('scaling', StandardScaler()),
                            ('sampling', SMOTE()),
                            ('feature_selection', SelectFromModel(ExtraTreesClassifier(random_state=2), prefit=False)),
                           ('algo', KNeighborsClassifier())
                           ])

In [ ]:
model4 = GridSearchCV(pipeline4, param_grid=parameter4, cv=3, n_jobs=-1, verbose=1)
model4_fit = model4.fit(X_train, y_train)

Fitting 3 folds for each of 90 candidates, totalling 270 fits


In [ ]:
prediction4 = model4_fit.predict(X_test)
print(classification_report(y_test, prediction4))
print(confusion_matrix(y_test, prediction4))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83      1035
           1       0.55      0.58      0.56       374

    accuracy                           0.76      1409
   macro avg       0.69      0.70      0.70      1409
weighted avg       0.76      0.76      0.76      1409

[[855 180]
 [158 216]]


In [ ]:
filename3 = 'model3_3.pkl'
joblib.dump(model3_fit, filename3)

['model3_3.pkl']

In [ ]:
X_test.head()

gender SeniorCitizen  ... MonthlyCharges TotalCharges
437     Male            No  ...         114.05      8468.20
2280  Female           Yes  ...         100.15       908.55
2235  Female            No  ...          78.35      3211.20
4460    Male            No  ...          78.20      1468.75
3761  Female            No  ...          82.65      5919.35

[5 rows x 19 columns]

#Load the model and make prediction

In [ ]:
pip install joblib

In [ ]:
import joblib
import pandas as pd

filename = '/content/randomforest.pkl'
loaded_model = joblib.load(filename)

data = {'gender':'Male', 'SeniorCitizen':'Yes', 'Partner':'Yes', 'Dependents':'Yes', 'tenure':72,
       'PhoneService':'Yes', 'MultipleLines':'Yes', 'InternetService':'DSL', 'OnlineSecurity':'Yes',
       'OnlineBackup':'Yes', 'DeviceProtection':'Yes', 'TechSupport':'Yes', 'StreamingTV':'Yes',
       'StreamingMovies':'Yes', 'Contract':'Two year', 'PaperlessBilling':'Yes', 'PaymentMethod':'Credit card (automatic)',
       'MonthlyCharges':82.65, 'TotalCharges':100}


In [ ]:
loaded_model

Pipeline(memory=None,
         steps=[('preprocessing',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('numeric',
                                                  Pipeline(memory=None,
                                                           steps=[('imputer',
                                                                   SimpleImputer(add_indicator=False,
                                                                                 copy=True,
                                                                                 fill_value=None,
                                                                                 missing_values=nan,
                                                                                 strategy='mean',
                                                          

In [ ]:
df_input = pd.DataFrame(data, index=[0])
result = loaded_model.predict(df_input)
result



array([0])

In [ ]:
for i in result:
  int_result = int(i)
  if (int_result == 0):
    decision = 'No'
  elif (int_result==1):
    decision = 'Yes'
  else:
    decison = 'Not defined'

print('Possibility to deposit is ', decision)

Possibility to deposit is  No


In [ ]:
for i in range(len(cats)):
  print(cats[i], ' = ' , df[cats[i]].unique())

gender  =  ['Female' 'Male']
SeniorCitizen  =  ['No' 'Yes']
Partner  =  ['Yes' 'No']
Dependents  =  ['No' 'Yes']
PhoneService  =  ['No' 'Yes']
MultipleLines  =  ['No phone service' 'No' 'Yes']
InternetService  =  ['DSL' 'Fiber optic' 'No']
OnlineSecurity  =  ['No' 'Yes' 'No internet service']
OnlineBackup  =  ['Yes' 'No' 'No internet service']
DeviceProtection  =  ['No' 'Yes' 'No internet service']
TechSupport  =  ['No' 'Yes' 'No internet service']
StreamingTV  =  ['No' 'Yes' 'No internet service']
StreamingMovies  =  ['No' 'Yes' 'No internet service']
Contract  =  ['Month-to-month' 'One year' 'Two year']
PaperlessBilling  =  ['Yes' 'No']
PaymentMethod  =  ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
